suppressPackageStartupMessages({library(readxl);library(dplyr)})
source(file.path(dirname(sub("^--file=", "", commandArgs(FALSE)[grepl("^--file=", commandArgs(FALSE))][1])), "_common.R"))
dat<-read_excel(resolve_data_path(),sheet="Baseline_to_FinalFU"); g<-"VAS_Response_Final"
ms<-function(x,sign=FALSE){x<-x[!is.na(x)];if(!length(x))return("NA");pre<-if(sign&&mean(x)>0)"+" else "";sprintf("%s%.2f ± %.2f (%d)",pre,mean(x),sd(x),length(x))}; np<-function(x,lev){x<-x[!is.na(x)];n<-sum(x==lev);sprintf("%d (%.1f)",n,100*n/length(x))}
rows<-list();addk<-function(label,var,sign=FALSE){p<-kruskal.test(dat[[var]]~factor(dat[[g]],levels=CHANGE_LEVELS))$p.value;data.frame(Variable=label,Decreased=ms(dat[[var]][dat[[g]]=="Decreased"],sign),Maintained=ms(dat[[var]][dat[[g]]=="Maintained"],sign),Increased=ms(dat[[var]][dat[[g]]=="Increased"],sign),P_value=fmt_p(p),check.names=FALSE)}
rows[[length(rows)+1]]<-addk("Baseline VAS","Baseline_VAS")
base_mod<-dat$Baseline_Pain_Group_2L==MODSEV;p<-chisq.test(table(base_mod,dat[[g]]),correct=FALSE)$p.value;rows[[length(rows)+1]]<-data.frame(Variable="Moderate-to-severe baseline pain, n (%)",Decreased=np(base_mod[dat[[g]]=="Decreased"],TRUE),Maintained=np(base_mod[dat[[g]]=="Maintained"],TRUE),Increased=np(base_mod[dat[[g]]=="Increased"],TRUE),P_value=fmt_p(p),check.names=FALSE)
rows[[length(rows)+1]]<-addk("Final VAS","Final_VAS");p<-chisq.test(table(dat$Final_VAS_Zero,dat[[g]]),correct=FALSE)$p.value;rows[[length(rows)+1]]<-data.frame(Variable="Final VAS = 0, n (%)",Decreased=np(dat$Final_VAS_Zero[dat[[g]]=="Decreased"],1),Maintained=np(dat$Final_VAS_Zero[dat[[g]]=="Maintained"],1),Increased=np(dat$Final_VAS_Zero[dat[[g]]=="Increased"],1),P_value=fmt_p(p),check.names=FALSE)
for(x in list(c("ΔVAS, final − baseline","Delta_VAS_Final","F"),c("Baseline CMO, mm","Baseline_CMO","F"),c("Final CMO, mm","Final_CMO","F"),c("ΔCMO, mm, final − baseline","Delta_CMO_Final","T"),c("Baseline MMO, mm","Baseline_MMO","F"),c("Final MMO, mm","Final_MMO","F"),c("ΔMMO, mm, final − baseline","Delta_MMO_Final","T"),c("Baseline pain-location burden score","Baseline_Pain_Burden","F"),c("Final pain-location burden score","Final_Pain_Burden","F"),c("ΔPain-location burden, final − baseline","Delta_Pain_Burden_Final","F")))rows[[length(rows)+1]]<-addk(x[1],x[2],x[3]=="T")
for(spec in list(list("CMO","CMO_Response_Final",c("Increased","Maintained","Decreased")),list("MMO","MMO_Response_Final",c("Increased","Maintained","Decreased")),list("Pain-location burden","Pain_Burden_Response_Final",c("Decreased","Maintained","Increased")))){p<-chisq.test(table(dat[[spec[[2]]]],dat[[g]]),correct=FALSE)$p.value;for(i in seq_along(spec[[3]])){lev<-spec[[3]][i];rows[[length(rows)+1]]<-data.frame(Variable=paste(spec[[1]],tolower(lev),", n (%)"),Decreased=np(dat[[spec[[2]]]][dat[[g]]=="Decreased"],lev),Maintained=np(dat[[spec[[2]]]][dat[[g]]=="Maintained"],lev),Increased=np(dat[[spec[[2]]]][dat[[g]]=="Increased"],lev),P_value=if(i==1)fmt_p(p) else "",check.names=FALSE)}}
fu<-read_excel(resolve_data_path(),sheet="Final_FU_191")%>%select(Study_ID,Pain_Present);m<-dat%>%select(Study_ID,VAS_Response_Final)%>%left_join(fu,by="Study_ID");p<-chisq.test(table(m$Pain_Present,m$VAS_Response_Final),correct=FALSE)$p.value;rows[[length(rows)+1]]<-data.frame(Variable="Pain absent at final follow-up, n (%)",Decreased=np(m$Pain_Present[m$VAS_Response_Final=="Decreased"],0),Maintained=np(m$Pain_Present[m$VAS_Response_Final=="Maintained"],0),Increased=np(m$Pain_Present[m$VAS_Response_Final=="Increased"],0),P_value=fmt_p(p),check.names=FALSE)
tab<-bind_rows(rows);names(tab)[2:4]<-c("VAS decreased (n=102)","VAS maintained (n=77)","VAS increased (n=12)");write.csv(tab,file.path(output_dir(),"Supplementary_Table_S3.csv"),row.names=FALSE,fileEncoding="UTF-8");print(tab)
