suppressPackageStartupMessages({library(readxl);library(dplyr)})
source(file.path(dirname(sub("^--file=", "", commandArgs(FALSE)[grepl("^--file=", commandArgs(FALSE))][1])), "_common.R"))
dat<-read_excel(resolve_data_path(),sheet="Baseline_to_FinalFU")
cont<-list(c("Final VAS","Final_VAS"),c("ΔVAS, final − baseline","Delta_VAS_Final"),c("Final CMO, mm","Final_CMO"),c("ΔCMO, mm, final − baseline","Delta_CMO_Final"),c("Final MMO, mm","Final_MMO"),c("ΔMMO, mm, final − baseline","Delta_MMO_Final"),c("Final pain-location burden score","Final_Pain_Burden"),c("ΔPain-location burden, final − baseline","Delta_Pain_Burden_Final"))
raw<-sapply(cont,function(x)wilcox.test(dat[[x[2]]][dat$Baseline_Pain_Group_2L==MILD],dat[[x[2]]][dat$Baseline_Pain_Group_2L==MODSEV],exact=FALSE)$p.value)
raw<-c(raw,categorical_p(table(dat$Final_VAS_Zero,dat$Baseline_Pain_Group_2L)),chisq.test(table(dat$VAS_Response_Final,dat$Baseline_Pain_Group_2L),correct=FALSE)$p.value,chisq.test(table(dat$Pain_Burden_Response_Final,dat$Baseline_Pain_Group_2L),correct=FALSE)$p.value)
keys<-c(sapply(cont,`[[`,1),"Final VAS = 0, n (%)","VAS change distribution","Pain-location burden change distribution");adj<-p.adjust(raw,"BH");pm<-setNames(Map(c,raw,adj),keys)
ms<-function(x,sign=FALSE){x<-x[!is.na(x)];pre<-if(sign&&mean(x)>0)"+" else "";sprintf("%s%.2f ± %.2f (%d)",pre,mean(x),sd(x),length(x))};np<-function(x,lev){x<-x[!is.na(x)];n<-sum(x==lev);sprintf("%d (%.1f)",n,100*n/length(x))}
rows<-list(data.frame(Outcome="Patients with available final follow-up, n",Overall=nrow(dat),Mild=sum(dat$Baseline_Pain_Group_2L==MILD),Moderate_to_severe=sum(dat$Baseline_Pain_Group_2L==MODSEV),P_value="",FDR_adjusted_P_value="",check.names=FALSE))
add_cont<-function(label,var,sign=FALSE){pa<-pm[[label]];data.frame(Outcome=label,Overall=ms(dat[[var]],sign),Mild=ms(dat[[var]][dat$Baseline_Pain_Group_2L==MILD],sign),Moderate_to_severe=ms(dat[[var]][dat$Baseline_Pain_Group_2L==MODSEV],sign),P_value=fmt_p(pa[1]),FDR_adjusted_P_value=fmt_p(pa[2]),check.names=FALSE)}
rows[[length(rows)+1]]<-add_cont("Final VAS","Final_VAS")
pa<-pm[["Final VAS = 0, n (%)"]];rows[[length(rows)+1]]<-data.frame(Outcome="Final VAS = 0, n (%)",Overall=np(dat$Final_VAS_Zero,1),Mild=np(dat$Final_VAS_Zero[dat$Baseline_Pain_Group_2L==MILD],1),Moderate_to_severe=np(dat$Final_VAS_Zero[dat$Baseline_Pain_Group_2L==MODSEV],1),P_value=fmt_p(pa[1]),FDR_adjusted_P_value=fmt_p(pa[2]),check.names=FALSE)
pa<-pm[["VAS change distribution"]];for(i in seq_along(CHANGE_LEVELS)){lev<-CHANGE_LEVELS[i];rows[[length(rows)+1]]<-data.frame(Outcome=paste("VAS",tolower(lev),"from baseline, n (%)"),Overall=np(dat$VAS_Response_Final,lev),Mild=np(dat$VAS_Response_Final[dat$Baseline_Pain_Group_2L==MILD],lev),Moderate_to_severe=np(dat$VAS_Response_Final[dat$Baseline_Pain_Group_2L==MODSEV],lev),P_value=if(i==1)fmt_p(pa[1]) else "",FDR_adjusted_P_value=if(i==1)fmt_p(pa[2]) else "",check.names=FALSE)}
rows[[length(rows)+1]]<-add_cont("ΔVAS, final − baseline","Delta_VAS_Final")
rows[[length(rows)+1]]<-add_cont("Final CMO, mm","Final_CMO");rows[[length(rows)+1]]<-add_cont("ΔCMO, mm, final − baseline","Delta_CMO_Final",TRUE);rows[[length(rows)+1]]<-add_cont("Final MMO, mm","Final_MMO");rows[[length(rows)+1]]<-add_cont("ΔMMO, mm, final − baseline","Delta_MMO_Final",TRUE);rows[[length(rows)+1]]<-add_cont("Final pain-location burden score","Final_Pain_Burden");rows[[length(rows)+1]]<-add_cont("ΔPain-location burden, final − baseline","Delta_Pain_Burden_Final")
pa<-pm[["Pain-location burden change distribution"]];for(i in seq_along(CHANGE_LEVELS)){lev<-CHANGE_LEVELS[i];rows[[length(rows)+1]]<-data.frame(Outcome=paste("Pain-location burden",tolower(lev),", n (%)"),Overall=np(dat$Pain_Burden_Response_Final,lev),Mild=np(dat$Pain_Burden_Response_Final[dat$Baseline_Pain_Group_2L==MILD],lev),Moderate_to_severe=np(dat$Pain_Burden_Response_Final[dat$Baseline_Pain_Group_2L==MODSEV],lev),P_value=if(i==1)fmt_p(pa[1]) else "",FDR_adjusted_P_value=if(i==1)fmt_p(pa[2]) else "",check.names=FALSE)}
tab<-bind_rows(rows);write.csv(tab,file.path(output_dir(),"Table_4.csv"),row.names=FALSE,fileEncoding="UTF-8");print(tab)
